apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.17.1-1.1 # Use a specific version for stability
        command: ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
        - name: var-log-volume
          mountPath: /var/log
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: fluentd-config-pvc
      - name: var-log-volume
        emptyDir: {}
