apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluentd-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/sprtndilip99/GitLoki/kube/fluentd.conf
    type: DirectoryOrCreate
