apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |
    scrape_configs:
- job_name: kubernetes
  kubernetes:
    # ... (Kubernetes configuration as shown above) ...
- job_name: my-app # Add more jobs for other applications
  static_configs:
  - targets:
    - http://34.68.181.200:3000/ # Replace with your application's address and port
    labels:
      job: my-app
  pipeline_stages:
  - regex:
      expression: '^(?<stream>.*)$'
      source: logs
  - loki:
      url: http://34.70.241.221:3100/loki/api/v1/push # Replace with your Loki service URL
      labels:
        job: my-app
