apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-loki
  template:
    metadata:
      labels:
        app: fluentd-loki
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.16.6-1.0
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: fluentd-config-test
          mountPath: /fluentd/etc
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -f http://localhost:24224 || exit 1"]
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: fluentd-config-test
        hostPath:
          path: /home/sprtndilip99/GitLoki/kube/fluentd.conf # <--- Directory containing fluentd.conf
