apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-loki
  template:
    metadata:
      labels:
        app: fluentd-loki
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.16.6-1.0 # Or a specific version
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        resources:
          requests:
            cpu: 200m # Increased CPU request
            memory: 512Mi # Increased memory request
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -f http://localhost:24224 || exit 1"]
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-loki-config
