apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-loki
  template:
    metadata:
      labels:
        app: fluentd-loki
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.16.6-1.0 # Or a specific version
        ports:
        - containerPort: 24224 # Fluentd's default port
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-loki-config
