apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd-sa
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.17.1-1.1 # Or your chosen image
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/
        - name: var-log
          mountPath: /var/log
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: var-log
        emptyDir: {}
