apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-loki-config
data:
  fluentd.conf: |
    <source>
      @type kubernetes_metadata
      tag kubernetes.var.log
      <parse>
        @type multi_format
        format json
      </parse>
    </source>

    <match kubernetes.var.log>
      @type loki
      loki_url "http://34.70.241.221:3100/" # Replace with your Loki service
      labels {
        job = "kubernetes"
        container = "${container_name}"
        namespace = "${namespace}"
        pod = "${pod_name}"
      }
    </match>

    # Add more <match> sections for other log sources as needed.  Example below:
    <match **>
      @type stdout
    </match>

