apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail-role-binding
  namespace: game
subjects:
- kind: ServiceAccount
  name: promtail-sa
  namespace: game
roleRef:
  kind: Role
  name: promtail-role
  apiGroup: rbac.authorization.k8s.io
