apiVersion: v1
kind: Service
metadata:
  name: testford-service
  namespace: logging
spec:
  type: NodePort
  selector:
    app: testford
  ports:
    - protocol: TCP
      port: 3000       # The port that the service will listen on
      targetPort: 3000 # The port on the container
      nodePort: 30007 # A specific node port (must be between 30000-32767)
